### ISSUE TITLE
Could you give some examples about how to use this library?

### ISSUE THREAD

**Issue by zhajio1988** [Paebbels/pyIPXACT#3]

**Comment by Paebbels** [comment]
This library is in pre-alpha state. It is currently a case study on how to quickly translate IP-XACT XML files into an object model. It can already handle some of the constructs, but not all of them.

As this project is in pre-alpha state I didn't write a full documentation.

----------
Do you like to use this library or want to help implement more tags? If so I could write some documentation in the next days including a tiny example.

**Comment by Paebbels** [comment]
A little bit of test-code can be found here: https://github.com/Paebbels/pyIPXACT/blob/master/Test.py?ts=2

**Comment by zhajio1988** [comment]
@Paebbels  thanks for your immediate reply.  I just search the lib for parsing IPXACT and found your source. Thanks for your work.
